### ISSUE TITLE
Does this repository still work?

### ISSUE THREAD

**Issue by mckarthik7** [flatironinstitute/spikeforest_recordings#7]
None of the sha1dir links seem to download anymore. If this repository is not maintained/if there is a new version, please update/deprecate/archive it. Thank you

**Comment by jsoules** [comment]
@mckarthik7 
Thanks for reaching out--yes, the protocol and infrastructure used to distribute the files has been through some revisions.

We have been migrating the old files to the current protocol versions. Up-to-date links are located at https://github.com/flatironinstitute/spikeforest -- you'll be specifically interested in https://github.com/flatironinstitute/spikeforest/tree/main/spikeforest/load_spikeforest_recordings and https://github.com/flatironinstitute/spikeforest/tree/main/spikeforest/load_spikeforest_sorting_outputs. Not everything is migrated yet; if there's a particular recording or sorting you're looking for, please post a follow-up and we'll prioritize making it available under the new protocol.

Note, you'll need to install the spikeforest repository locally (by cloning the repo and using `pip install -e /REPO/DIR` instead of using the version from pypi).

Sorry for the confusion here--we have a good bit of a backlog on updating the documentation and pointing all resources to match the current state of play.

**Comment by mckarthik7** [comment]
I see, thank you!
I tried setting up the new repositories, and so far I have been able to list some recordings. The ones I am interested in specifically are the manual franklab recordings. It would be great if these can be uploaded again. I would appreciate it if you let me know when you do so.

**Comment by jsoules** [comment]
Hi @mckarthik7
Glad to hear it's working so far!
We've added the Franklab recordings that you requested; see the updated examples for pulling recordings and sorting objects over at the SpikeForest repo: https://github.com/flatironinstitute/spikeforest/tree/main/examples -- you just need to specify the correct URI.

In the near future, we may break these scripts into separate versions for each set of recordings, but I expect the code you need will still be in that directory. Please feel free to reach out further if we can give you further assistance.
